### ISSUE TITLE
**Cards**

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/predicting_wine_quality#2]
**THIS IS A TEST ISSUE FOR YAIR TO DO**

Cards can be added to your board to track the progress of issues and pull requests. You can also add note cards, like this one!

**Comment by gutermanyair** [comment]
Thanks!

**Comment by SonQBChau** [comment]
testing github bot

**Comment by NikitaShymberg** [comment]
Closing the test issue
