### ISSUE TITLE
[Discussion] Should we use type hints?

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/predicting_wine_quality#26]
Hi team, what are your thoughts on type hints. Should we use them for this project? All the time or sometimes?

I like them but it is an extra step of work and sometimes you have to import additional things to give type hints about them.

**Comment by gutermanyair** [comment]
I think it is fine if we don't include them, I think maybe if we have extra time at the end of the week and we want to go back and add them in everywhere we can but at this point let's just work on getting everything done:)
