### ISSUE TITLE
Submit Milestone 1

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/predicting_wine_quality#8]

**Comment by NikitaShymberg** [comment]
Hey team, we forgot to pick someone to submit milestone 1 this week. Does anyone want to volunteer?

**Comment by SonQBChau** [comment]
If you are ok with submitting after Sat (the deadline this week is Sunday), I can do it

**Comment by aldojasb** [comment]
I'm good with that! No worries from my side.

**Comment by NikitaShymberg** [comment]
Submitted!
